apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wenoti
  name: wenoti
  namespace: wechat  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wenoti
  template:
    metadata:
      labels:
        app: wenoti
    spec:
      containers:
      - image: runlongreg.azurecr.io/wechatcom:alphav2.10.3
        imagePullPolicy: "Always"                                                                              
        name: wechatcom
        ports:
        - containerPort: 8848
          name: api
          protocol: TCP
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "wechatnotify"
#        env:
#        - name: PYTHONUNBUFFERED
#          value: "0"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wenoti
  name: wenoti
  namespace: wechat
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: stable
spec:
  loadBalancerIP: 20.198.66.35
  ports:
  - port: 8848
    name: server-api
    protocol: TCP
    targetPort: 8848
  selector:
    app: wenoti
  type: LoadBalancer
  externalTrafficPolicy: Local
